name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push package to npmjs.com
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - run: sed -i 's/ssh:/https:/g' ./package-lock.json # avoid issue caused by using ssh from github actions
    - run: npm install
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
